# Generated by Django 5.2.8 on 2025-11-21 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('consulta', 'Consulta')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consejo_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario (Consejo)',
                'verbose_name_plural': 'Usuarios (Consejo)',
                'unique_together': {('user',)},
            },
        ),
    ]
