# Generated by Django 4.2.26 on 2026-02-20 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_consejo', '0002_consejodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejouser',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consejo_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
