# Generated by Django 5.2.8 on 2025-11-22 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estimulos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimulosDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('archivo_pdf', models.FileField(upload_to='estimulos/pdf/', verbose_name='Archivo PDF')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimulos_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento (Estímulos)',
                'verbose_name_plural': 'Documentos (Estímulos)',
                'db_table': 'estimulos_documentos',
                'ordering': ['-creado'],
            },
        ),
    ]
